// <auto-generated />
using System;
using CarbonTrace.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CarbonTrace.Infrastructure.Migrations
{
    [DbContext(typeof(CarbonTraceContext))]
    [Migration("20260526233744_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Alerta", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EMISSAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("IdAnalise")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ANALISE");

                    b.Property<string>("NivelCriticidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("NIVEL_CRITICIDADE");

                    b.HasKey("Id");

                    b.HasIndex("IdAnalise");

                    b.ToTable("CT_ALERTA", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.AlertaOrgao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ALERTA_ORGAO");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataNotificacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NOTIFICACAO");

                    b.Property<string>("IdAlerta")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<string>("IdOrgao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ORGAO");

                    b.Property<string>("StatusNotificacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS_NOTIFICACAO");

                    b.HasKey("Id");

                    b.HasIndex("IdOrgao");

                    b.HasIndex("IdAlerta", "IdOrgao")
                        .IsUnique();

                    b.ToTable("CT_ALERTA_ORGAO", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Analise", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ANALISE");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<double>("AreaDesmatadaKm2")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("AREA_DESMATADA_KM2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ANALISE");

                    b.Property<string>("IdImagem")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_IMAGEM");

                    b.Property<double>("PercentualVariacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PERCENTUAL_VARIACAO");

                    b.Property<string>("StatusAlerta")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS_ALERTA");

                    b.HasKey("Id");

                    b.HasIndex("IdImagem");

                    b.ToTable("CT_ANALISE", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Estado", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(2)")
                        .HasColumnName("SIGLA");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("CT_ESTADO", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.ImagemSatelital", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_IMAGEM");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataCaptura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CAPTURA");

                    b.Property<string>("IdRegiao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("IdSatelite")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_SATELITE");

                    b.Property<double>("ResolucaoMetros")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("RESOLUCAO_METROS");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("URL_IMAGEM");

                    b.HasKey("Id");

                    b.HasIndex("IdRegiao");

                    b.HasIndex("IdSatelite");

                    b.ToTable("CT_IMAGEM_SATELITAL", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_OCORRENCIA");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<double>("AreaEstimadaKm2")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("AREA_ESTIMADA_KM2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_OCORRENCIA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("IdRegiao")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("IdRegiao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CT_OCORRENCIA", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.OrgaoAmbiental", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ORGAO");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("EmailContato")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("EMAIL_CONTATO");

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.ToTable("CT_ORGAO_AMBIENTAL", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Regiao", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<double>("AreaKm2")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("AREA_KM2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.ToTable("CT_REGIAO", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Relatorio", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_RELATORIO");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_GERACAO");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime>("PeriodoFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PERIODO_FIM");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PERIODO_INICIO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CT_RELATORIO", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Satelite", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_SATELITE");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("AGENCIA");

                    b.Property<double>("AltitudeKm")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("ALTITUDE_KM");

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO_LANCAMENTO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CT_SATELITE", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("CT_USUARIO", (string)null);
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.Analise", "Analise")
                        .WithMany("Alertas")
                        .HasForeignKey("IdAnalise")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analise");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.AlertaOrgao", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.Alerta", "Alerta")
                        .WithMany("AlertasOrgaos")
                        .HasForeignKey("IdAlerta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarbonTrace.Domain.Entities.OrgaoAmbiental", "OrgaoAmbiental")
                        .WithMany("AlertasOrgaos")
                        .HasForeignKey("IdOrgao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("OrgaoAmbiental");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Analise", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.ImagemSatelital", "ImagemSatelital")
                        .WithMany("Analises")
                        .HasForeignKey("IdImagem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImagemSatelital");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.ImagemSatelital", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.Regiao", "Regiao")
                        .WithMany("ImagensSatelitais")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarbonTrace.Domain.Entities.Satelite", "Satelite")
                        .WithMany("ImagensSatelitais")
                        .HasForeignKey("IdSatelite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.Regiao", "Regiao")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarbonTrace.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.OrgaoAmbiental", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.Estado", "Estado")
                        .WithMany("OrgaosAmbientais")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Regiao", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.Estado", "Estado")
                        .WithMany("Regioes")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("CarbonTrace.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Relatorios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Alerta", b =>
                {
                    b.Navigation("AlertasOrgaos");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Analise", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Estado", b =>
                {
                    b.Navigation("OrgaosAmbientais");

                    b.Navigation("Regioes");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.ImagemSatelital", b =>
                {
                    b.Navigation("Analises");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.OrgaoAmbiental", b =>
                {
                    b.Navigation("AlertasOrgaos");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("ImagensSatelitais");

                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Satelite", b =>
                {
                    b.Navigation("ImagensSatelitais");
                });

            modelBuilder.Entity("CarbonTrace.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Ocorrencias");

                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
